### ISSUE TITLE
Homework 1 Question 3

### ISSUE THREAD

**Issue by anyezijue49** [anyezijue49/stat679work#2]
Hi Professor @cecileane

Here is my homework.
https://github.com/anyezijue49/stat679work/commit/a4d7f241e1d22f99798b645008b09155880c45a3
Please make sure that your current directory include directories **log** and **out** when you run **summarizeSNaQres.sh**.
Thank you

Sheng Guo

**Comment by cecileane** [comment]
Thanks Sheng! This is my way of asking Pablo (@pgonzalez6) and Cora (@coraallencoleman) try your script and provide feedback on it.

**Comment by coraallensavietta** [comment]
Hi Sheng,

Great work! I like the way you organized your code into one loop with nested sub-loops. It's clear, lean and works pretty well. Nice job.

My first concern is that your work runs not only on the timetest files, but also on bT1, net1, and newtry1 files. If you narrow the search in your opening statement, "for filename in _.log" to include only timetest files in the log folder using something like, "for file in timetest_". I think this may also fix the misordering in your csv file.

To make your code even clearer, it would be great to include documentation and notes (commented out) within the file, including information at the top of the file about which files the script works on, where it should be run, and what it produces. It would also be helpful to have some notes throughout the loop, describing what each statement creates.

I liked your use of the concepts we've learned in class so far: loops, grep, and sed. The way you use if and elif to create variables under3460, under3450, under3440 was especially clever.

Thanks for sharing your work! It was a pleasure to learn from your code.

Best,
Cora

**Comment by cecileane** [comment]
Hi all, 
It's good actually, that Sheng's script runs on all the analysis files: including `bT1`, `net1_snaq` etc. These data are messy, like almost all real data sets... I am sorry that the description didn't clarify what data files to include or not.

**Comment by pgonzalez6** [comment]
Hi Sheng, 

I was looking at the script and in my opinion is very clear what is sought perform. In particular I believe that exercise 3 is a very elegant way to solve a problem that I had not been solved. Taking the same ideas of this part of the script is that I could finally do it. However, I think it might be some changes in order to reduce the size of the script into more efficient for those who read it. At first, each of the variables can be defined at the beginning of each lines, for example CPU Time = $ (grep ....) and then printed with the echo function at the end of the script and stored all together in the same table, this may help to reduce several lines of code. Second, possibly there is a way to define the variables under3440, 3450 and 3460 where it is not necessary to generate the t2.txt file, but directly you can define the variables in the loop, this also reduces slightly the length of the script. I tried it in my code and it is working well. In general terms I think that you have a very good use of all the concepts and functions that we were working in classes took, maybe it would be positive to incorporate more comments on the lines of code to be more explanatory with those who are not within the course as us.

Regards, Pablo
